package com.example.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo implements Serializable {


    @Id
    @DynamoDBIgnore
    private ProductId productId;

    @DynamoDBAttribute
    private String msrp;

    @DynamoDBAttribute
    private String cost;

    @DynamoDBAttribute
    private int count;

    public ProductInfo() {
    }

    public ProductInfo(String msrp, String cost, ProductId productId, int count) {
        this.msrp = msrp;
        this.cost = cost;
        this.productId = productId;
        this.count = count;
    }

    @DynamoDBRangeKey
    public Date getCreatedAt() {
        return productId != null ? productId.getCreatedAt() : null;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return productId != null ? productId.getId() : null;
    }

    public void setCreatedAt(Date createdAt) {
        if (null == productId) {
            productId = new ProductId();
        }
        productId.setCreatedAt(createdAt);
    }

    public void setId(final String id) {
        if (null == productId) {
            productId = new ProductId();
        }
        productId.setId(id);
    }

    public ProductId getProductId() {
        return productId;
    }


    public void setProductId(ProductId productId) {
        this.productId = productId;
    }

    public String getMsrp() {
        return msrp;
    }

    public void setMsrp(String msrp) {
        this.msrp = msrp;
    }

    public String getCost() {
        return cost;
    }

    public void setCost(String cost) {
        this.cost = cost;
    }


    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    @Override
    public String toString() {
        return "ProductInfo{" +
                "productId=" + productId +
                ", msrp='" + msrp + '\'' +
                ", cost='" + cost + '\'' +
                ", count=" + count +
                '}';
    }
}
